/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VTokenRouteImport } from './routes/v.$token'
import { Route as KundeTokenRouteImport } from './routes/kunde.$token'
import { Route as BTokenRouteImport } from './routes/b.$token'
import { Route as AuthenticatedStatistikRouteImport } from './routes/_authenticated.statistik'
import { Route as AuthenticatedPlanRouteImport } from './routes/_authenticated.plan'
import { Route as AuthenticatedNachrichtenRouteImport } from './routes/_authenticated.nachrichten'
import { Route as AuthenticatedMitarbeiterRouteImport } from './routes/_authenticated.mitarbeiter'
import { Route as AuthenticatedImportRouteImport } from './routes/_authenticated.import'
import { Route as AuthenticatedExportRouteImport } from './routes/_authenticated.export'
import { Route as AuthenticatedEinrichtungenRouteImport } from './routes/_authenticated.einrichtungen'
import { Route as AuthenticatedDispoRouteImport } from './routes/_authenticated.dispo'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated.dashboard'
import { Route as AuthenticatedBedarfRouteImport } from './routes/_authenticated.bedarf'
import { Route as AuthenticatedAnfragenRouteImport } from './routes/_authenticated.anfragen'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VTokenRoute = VTokenRouteImport.update({
  id: '/v/$token',
  path: '/v/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const KundeTokenRoute = KundeTokenRouteImport.update({
  id: '/kunde/$token',
  path: '/kunde/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const BTokenRoute = BTokenRouteImport.update({
  id: '/b/$token',
  path: '/b/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedStatistikRoute = AuthenticatedStatistikRouteImport.update({
  id: '/statistik',
  path: '/statistik',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPlanRoute = AuthenticatedPlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedNachrichtenRoute =
  AuthenticatedNachrichtenRouteImport.update({
    id: '/nachrichten',
    path: '/nachrichten',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMitarbeiterRoute =
  AuthenticatedMitarbeiterRouteImport.update({
    id: '/mitarbeiter',
    path: '/mitarbeiter',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedImportRoute = AuthenticatedImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedExportRoute = AuthenticatedExportRouteImport.update({
  id: '/export',
  path: '/export',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedEinrichtungenRoute =
  AuthenticatedEinrichtungenRouteImport.update({
    id: '/einrichtungen',
    path: '/einrichtungen',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDispoRoute = AuthenticatedDispoRouteImport.update({
  id: '/dispo',
  path: '/dispo',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBedarfRoute = AuthenticatedBedarfRouteImport.update({
  id: '/bedarf',
  path: '/bedarf',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAnfragenRoute = AuthenticatedAnfragenRouteImport.update({
  id: '/anfragen',
  path: '/anfragen',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/anfragen': typeof AuthenticatedAnfragenRoute
  '/bedarf': typeof AuthenticatedBedarfRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/dispo': typeof AuthenticatedDispoRoute
  '/einrichtungen': typeof AuthenticatedEinrichtungenRoute
  '/export': typeof AuthenticatedExportRoute
  '/import': typeof AuthenticatedImportRoute
  '/mitarbeiter': typeof AuthenticatedMitarbeiterRoute
  '/nachrichten': typeof AuthenticatedNachrichtenRoute
  '/plan': typeof AuthenticatedPlanRoute
  '/statistik': typeof AuthenticatedStatistikRoute
  '/b/$token': typeof BTokenRoute
  '/kunde/$token': typeof KundeTokenRoute
  '/v/$token': typeof VTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/anfragen': typeof AuthenticatedAnfragenRoute
  '/bedarf': typeof AuthenticatedBedarfRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/dispo': typeof AuthenticatedDispoRoute
  '/einrichtungen': typeof AuthenticatedEinrichtungenRoute
  '/export': typeof AuthenticatedExportRoute
  '/import': typeof AuthenticatedImportRoute
  '/mitarbeiter': typeof AuthenticatedMitarbeiterRoute
  '/nachrichten': typeof AuthenticatedNachrichtenRoute
  '/plan': typeof AuthenticatedPlanRoute
  '/statistik': typeof AuthenticatedStatistikRoute
  '/b/$token': typeof BTokenRoute
  '/kunde/$token': typeof KundeTokenRoute
  '/v/$token': typeof VTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/anfragen': typeof AuthenticatedAnfragenRoute
  '/_authenticated/bedarf': typeof AuthenticatedBedarfRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/dispo': typeof AuthenticatedDispoRoute
  '/_authenticated/einrichtungen': typeof AuthenticatedEinrichtungenRoute
  '/_authenticated/export': typeof AuthenticatedExportRoute
  '/_authenticated/import': typeof AuthenticatedImportRoute
  '/_authenticated/mitarbeiter': typeof AuthenticatedMitarbeiterRoute
  '/_authenticated/nachrichten': typeof AuthenticatedNachrichtenRoute
  '/_authenticated/plan': typeof AuthenticatedPlanRoute
  '/_authenticated/statistik': typeof AuthenticatedStatistikRoute
  '/b/$token': typeof BTokenRoute
  '/kunde/$token': typeof KundeTokenRoute
  '/v/$token': typeof VTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/anfragen'
    | '/bedarf'
    | '/dashboard'
    | '/dispo'
    | '/einrichtungen'
    | '/export'
    | '/import'
    | '/mitarbeiter'
    | '/nachrichten'
    | '/plan'
    | '/statistik'
    | '/b/$token'
    | '/kunde/$token'
    | '/v/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/anfragen'
    | '/bedarf'
    | '/dashboard'
    | '/dispo'
    | '/einrichtungen'
    | '/export'
    | '/import'
    | '/mitarbeiter'
    | '/nachrichten'
    | '/plan'
    | '/statistik'
    | '/b/$token'
    | '/kunde/$token'
    | '/v/$token'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/anfragen'
    | '/_authenticated/bedarf'
    | '/_authenticated/dashboard'
    | '/_authenticated/dispo'
    | '/_authenticated/einrichtungen'
    | '/_authenticated/export'
    | '/_authenticated/import'
    | '/_authenticated/mitarbeiter'
    | '/_authenticated/nachrichten'
    | '/_authenticated/plan'
    | '/_authenticated/statistik'
    | '/b/$token'
    | '/kunde/$token'
    | '/v/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  BTokenRoute: typeof BTokenRoute
  KundeTokenRoute: typeof KundeTokenRoute
  VTokenRoute: typeof VTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v/$token': {
      id: '/v/$token'
      path: '/v/$token'
      fullPath: '/v/$token'
      preLoaderRoute: typeof VTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kunde/$token': {
      id: '/kunde/$token'
      path: '/kunde/$token'
      fullPath: '/kunde/$token'
      preLoaderRoute: typeof KundeTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/b/$token': {
      id: '/b/$token'
      path: '/b/$token'
      fullPath: '/b/$token'
      preLoaderRoute: typeof BTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/statistik': {
      id: '/_authenticated/statistik'
      path: '/statistik'
      fullPath: '/statistik'
      preLoaderRoute: typeof AuthenticatedStatistikRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/plan': {
      id: '/_authenticated/plan'
      path: '/plan'
      fullPath: '/plan'
      preLoaderRoute: typeof AuthenticatedPlanRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/nachrichten': {
      id: '/_authenticated/nachrichten'
      path: '/nachrichten'
      fullPath: '/nachrichten'
      preLoaderRoute: typeof AuthenticatedNachrichtenRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/mitarbeiter': {
      id: '/_authenticated/mitarbeiter'
      path: '/mitarbeiter'
      fullPath: '/mitarbeiter'
      preLoaderRoute: typeof AuthenticatedMitarbeiterRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/import': {
      id: '/_authenticated/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof AuthenticatedImportRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/export': {
      id: '/_authenticated/export'
      path: '/export'
      fullPath: '/export'
      preLoaderRoute: typeof AuthenticatedExportRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/einrichtungen': {
      id: '/_authenticated/einrichtungen'
      path: '/einrichtungen'
      fullPath: '/einrichtungen'
      preLoaderRoute: typeof AuthenticatedEinrichtungenRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dispo': {
      id: '/_authenticated/dispo'
      path: '/dispo'
      fullPath: '/dispo'
      preLoaderRoute: typeof AuthenticatedDispoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/bedarf': {
      id: '/_authenticated/bedarf'
      path: '/bedarf'
      fullPath: '/bedarf'
      preLoaderRoute: typeof AuthenticatedBedarfRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/anfragen': {
      id: '/_authenticated/anfragen'
      path: '/anfragen'
      fullPath: '/anfragen'
      preLoaderRoute: typeof AuthenticatedAnfragenRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAnfragenRoute: typeof AuthenticatedAnfragenRoute
  AuthenticatedBedarfRoute: typeof AuthenticatedBedarfRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDispoRoute: typeof AuthenticatedDispoRoute
  AuthenticatedEinrichtungenRoute: typeof AuthenticatedEinrichtungenRoute
  AuthenticatedExportRoute: typeof AuthenticatedExportRoute
  AuthenticatedImportRoute: typeof AuthenticatedImportRoute
  AuthenticatedMitarbeiterRoute: typeof AuthenticatedMitarbeiterRoute
  AuthenticatedNachrichtenRoute: typeof AuthenticatedNachrichtenRoute
  AuthenticatedPlanRoute: typeof AuthenticatedPlanRoute
  AuthenticatedStatistikRoute: typeof AuthenticatedStatistikRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAnfragenRoute: AuthenticatedAnfragenRoute,
  AuthenticatedBedarfRoute: AuthenticatedBedarfRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDispoRoute: AuthenticatedDispoRoute,
  AuthenticatedEinrichtungenRoute: AuthenticatedEinrichtungenRoute,
  AuthenticatedExportRoute: AuthenticatedExportRoute,
  AuthenticatedImportRoute: AuthenticatedImportRoute,
  AuthenticatedMitarbeiterRoute: AuthenticatedMitarbeiterRoute,
  AuthenticatedNachrichtenRoute: AuthenticatedNachrichtenRoute,
  AuthenticatedPlanRoute: AuthenticatedPlanRoute,
  AuthenticatedStatistikRoute: AuthenticatedStatistikRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  BTokenRoute: BTokenRoute,
  KundeTokenRoute: KundeTokenRoute,
  VTokenRoute: VTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
