/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VTokenRouteImport } from './routes/v.$token'
import { Route as TgVerfuegbarkeitRouteImport } from './routes/tg.verfuegbarkeit'
import { Route as MTokenRouteImport } from './routes/m.$token'
import { Route as KundeTokenRouteImport } from './routes/kunde.$token'
import { Route as BTokenRouteImport } from './routes/b.$token'
import { Route as AuthenticatedVerwaltungRouteImport } from './routes/_authenticated.verwaltung'
import { Route as AuthenticatedStatistikRouteImport } from './routes/_authenticated.statistik'
import { Route as AuthenticatedPosteingangRouteImport } from './routes/_authenticated.posteingang'
import { Route as AuthenticatedPlanRouteImport } from './routes/_authenticated.plan'
import { Route as AuthenticatedNachrichtenRouteImport } from './routes/_authenticated.nachrichten'
import { Route as AuthenticatedMitarbeiterRouteImport } from './routes/_authenticated.mitarbeiter'
import { Route as AuthenticatedImportRouteImport } from './routes/_authenticated.import'
import { Route as AuthenticatedExportRouteImport } from './routes/_authenticated.export'
import { Route as AuthenticatedEinrichtungenRouteImport } from './routes/_authenticated.einrichtungen'
import { Route as AuthenticatedDispoRouteImport } from './routes/_authenticated.dispo'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated.dashboard'
import { Route as AuthenticatedBedarfRouteImport } from './routes/_authenticated.bedarf'
import { Route as AuthenticatedAnfragenRouteImport } from './routes/_authenticated.anfragen'
import { Route as AuthenticatedAnfragenMitarbeiterRouteImport } from './routes/_authenticated.anfragen.mitarbeiter'
import { Route as AuthenticatedAnfragenKundenRouteImport } from './routes/_authenticated.anfragen.kunden'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as ApiPublicTelegramWebhookRouteImport } from './routes/api/public/telegram/webhook'
import { Route as ApiPublicEmailInboundRouteImport } from './routes/api/public/email/inbound'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VTokenRoute = VTokenRouteImport.update({
  id: '/v/$token',
  path: '/v/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const TgVerfuegbarkeitRoute = TgVerfuegbarkeitRouteImport.update({
  id: '/tg/verfuegbarkeit',
  path: '/tg/verfuegbarkeit',
  getParentRoute: () => rootRouteImport,
} as any)
const MTokenRoute = MTokenRouteImport.update({
  id: '/m/$token',
  path: '/m/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const KundeTokenRoute = KundeTokenRouteImport.update({
  id: '/kunde/$token',
  path: '/kunde/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const BTokenRoute = BTokenRouteImport.update({
  id: '/b/$token',
  path: '/b/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedVerwaltungRoute = AuthenticatedVerwaltungRouteImport.update({
  id: '/verwaltung',
  path: '/verwaltung',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedStatistikRoute = AuthenticatedStatistikRouteImport.update({
  id: '/statistik',
  path: '/statistik',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPosteingangRoute =
  AuthenticatedPosteingangRouteImport.update({
    id: '/posteingang',
    path: '/posteingang',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPlanRoute = AuthenticatedPlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedNachrichtenRoute =
  AuthenticatedNachrichtenRouteImport.update({
    id: '/nachrichten',
    path: '/nachrichten',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMitarbeiterRoute =
  AuthenticatedMitarbeiterRouteImport.update({
    id: '/mitarbeiter',
    path: '/mitarbeiter',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedImportRoute = AuthenticatedImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedExportRoute = AuthenticatedExportRouteImport.update({
  id: '/export',
  path: '/export',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedEinrichtungenRoute =
  AuthenticatedEinrichtungenRouteImport.update({
    id: '/einrichtungen',
    path: '/einrichtungen',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDispoRoute = AuthenticatedDispoRouteImport.update({
  id: '/dispo',
  path: '/dispo',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBedarfRoute = AuthenticatedBedarfRouteImport.update({
  id: '/bedarf',
  path: '/bedarf',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAnfragenRoute = AuthenticatedAnfragenRouteImport.update({
  id: '/anfragen',
  path: '/anfragen',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAnfragenMitarbeiterRoute =
  AuthenticatedAnfragenMitarbeiterRouteImport.update({
    id: '/mitarbeiter',
    path: '/mitarbeiter',
    getParentRoute: () => AuthenticatedAnfragenRoute,
  } as any)
const AuthenticatedAnfragenKundenRoute =
  AuthenticatedAnfragenKundenRouteImport.update({
    id: '/kunden',
    path: '/kunden',
    getParentRoute: () => AuthenticatedAnfragenRoute,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicTelegramWebhookRoute =
  ApiPublicTelegramWebhookRouteImport.update({
    id: '/api/public/telegram/webhook',
    path: '/api/public/telegram/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicEmailInboundRoute = ApiPublicEmailInboundRouteImport.update({
  id: '/api/public/email/inbound',
  path: '/api/public/email/inbound',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/anfragen': typeof AuthenticatedAnfragenRouteWithChildren
  '/bedarf': typeof AuthenticatedBedarfRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/dispo': typeof AuthenticatedDispoRoute
  '/einrichtungen': typeof AuthenticatedEinrichtungenRoute
  '/export': typeof AuthenticatedExportRoute
  '/import': typeof AuthenticatedImportRoute
  '/mitarbeiter': typeof AuthenticatedMitarbeiterRoute
  '/nachrichten': typeof AuthenticatedNachrichtenRoute
  '/plan': typeof AuthenticatedPlanRoute
  '/posteingang': typeof AuthenticatedPosteingangRoute
  '/statistik': typeof AuthenticatedStatistikRoute
  '/verwaltung': typeof AuthenticatedVerwaltungRoute
  '/b/$token': typeof BTokenRoute
  '/kunde/$token': typeof KundeTokenRoute
  '/m/$token': typeof MTokenRoute
  '/tg/verfuegbarkeit': typeof TgVerfuegbarkeitRoute
  '/v/$token': typeof VTokenRoute
  '/anfragen/kunden': typeof AuthenticatedAnfragenKundenRoute
  '/anfragen/mitarbeiter': typeof AuthenticatedAnfragenMitarbeiterRoute
  '/api/public/email/inbound': typeof ApiPublicEmailInboundRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/anfragen': typeof AuthenticatedAnfragenRouteWithChildren
  '/bedarf': typeof AuthenticatedBedarfRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/dispo': typeof AuthenticatedDispoRoute
  '/einrichtungen': typeof AuthenticatedEinrichtungenRoute
  '/export': typeof AuthenticatedExportRoute
  '/import': typeof AuthenticatedImportRoute
  '/mitarbeiter': typeof AuthenticatedMitarbeiterRoute
  '/nachrichten': typeof AuthenticatedNachrichtenRoute
  '/plan': typeof AuthenticatedPlanRoute
  '/posteingang': typeof AuthenticatedPosteingangRoute
  '/statistik': typeof AuthenticatedStatistikRoute
  '/verwaltung': typeof AuthenticatedVerwaltungRoute
  '/b/$token': typeof BTokenRoute
  '/kunde/$token': typeof KundeTokenRoute
  '/m/$token': typeof MTokenRoute
  '/tg/verfuegbarkeit': typeof TgVerfuegbarkeitRoute
  '/v/$token': typeof VTokenRoute
  '/anfragen/kunden': typeof AuthenticatedAnfragenKundenRoute
  '/anfragen/mitarbeiter': typeof AuthenticatedAnfragenMitarbeiterRoute
  '/api/public/email/inbound': typeof ApiPublicEmailInboundRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/anfragen': typeof AuthenticatedAnfragenRouteWithChildren
  '/_authenticated/bedarf': typeof AuthenticatedBedarfRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/dispo': typeof AuthenticatedDispoRoute
  '/_authenticated/einrichtungen': typeof AuthenticatedEinrichtungenRoute
  '/_authenticated/export': typeof AuthenticatedExportRoute
  '/_authenticated/import': typeof AuthenticatedImportRoute
  '/_authenticated/mitarbeiter': typeof AuthenticatedMitarbeiterRoute
  '/_authenticated/nachrichten': typeof AuthenticatedNachrichtenRoute
  '/_authenticated/plan': typeof AuthenticatedPlanRoute
  '/_authenticated/posteingang': typeof AuthenticatedPosteingangRoute
  '/_authenticated/statistik': typeof AuthenticatedStatistikRoute
  '/_authenticated/verwaltung': typeof AuthenticatedVerwaltungRoute
  '/b/$token': typeof BTokenRoute
  '/kunde/$token': typeof KundeTokenRoute
  '/m/$token': typeof MTokenRoute
  '/tg/verfuegbarkeit': typeof TgVerfuegbarkeitRoute
  '/v/$token': typeof VTokenRoute
  '/_authenticated/anfragen/kunden': typeof AuthenticatedAnfragenKundenRoute
  '/_authenticated/anfragen/mitarbeiter': typeof AuthenticatedAnfragenMitarbeiterRoute
  '/api/public/email/inbound': typeof ApiPublicEmailInboundRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/anfragen'
    | '/bedarf'
    | '/dashboard'
    | '/dispo'
    | '/einrichtungen'
    | '/export'
    | '/import'
    | '/mitarbeiter'
    | '/nachrichten'
    | '/plan'
    | '/posteingang'
    | '/statistik'
    | '/verwaltung'
    | '/b/$token'
    | '/kunde/$token'
    | '/m/$token'
    | '/tg/verfuegbarkeit'
    | '/v/$token'
    | '/anfragen/kunden'
    | '/anfragen/mitarbeiter'
    | '/api/public/email/inbound'
    | '/api/public/telegram/webhook'
    | '/lovable/email/queue/process'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/anfragen'
    | '/bedarf'
    | '/dashboard'
    | '/dispo'
    | '/einrichtungen'
    | '/export'
    | '/import'
    | '/mitarbeiter'
    | '/nachrichten'
    | '/plan'
    | '/posteingang'
    | '/statistik'
    | '/verwaltung'
    | '/b/$token'
    | '/kunde/$token'
    | '/m/$token'
    | '/tg/verfuegbarkeit'
    | '/v/$token'
    | '/anfragen/kunden'
    | '/anfragen/mitarbeiter'
    | '/api/public/email/inbound'
    | '/api/public/telegram/webhook'
    | '/lovable/email/queue/process'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/anfragen'
    | '/_authenticated/bedarf'
    | '/_authenticated/dashboard'
    | '/_authenticated/dispo'
    | '/_authenticated/einrichtungen'
    | '/_authenticated/export'
    | '/_authenticated/import'
    | '/_authenticated/mitarbeiter'
    | '/_authenticated/nachrichten'
    | '/_authenticated/plan'
    | '/_authenticated/posteingang'
    | '/_authenticated/statistik'
    | '/_authenticated/verwaltung'
    | '/b/$token'
    | '/kunde/$token'
    | '/m/$token'
    | '/tg/verfuegbarkeit'
    | '/v/$token'
    | '/_authenticated/anfragen/kunden'
    | '/_authenticated/anfragen/mitarbeiter'
    | '/api/public/email/inbound'
    | '/api/public/telegram/webhook'
    | '/lovable/email/queue/process'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  BTokenRoute: typeof BTokenRoute
  KundeTokenRoute: typeof KundeTokenRoute
  MTokenRoute: typeof MTokenRoute
  TgVerfuegbarkeitRoute: typeof TgVerfuegbarkeitRoute
  VTokenRoute: typeof VTokenRoute
  ApiPublicEmailInboundRoute: typeof ApiPublicEmailInboundRoute
  ApiPublicTelegramWebhookRoute: typeof ApiPublicTelegramWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v/$token': {
      id: '/v/$token'
      path: '/v/$token'
      fullPath: '/v/$token'
      preLoaderRoute: typeof VTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tg/verfuegbarkeit': {
      id: '/tg/verfuegbarkeit'
      path: '/tg/verfuegbarkeit'
      fullPath: '/tg/verfuegbarkeit'
      preLoaderRoute: typeof TgVerfuegbarkeitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/m/$token': {
      id: '/m/$token'
      path: '/m/$token'
      fullPath: '/m/$token'
      preLoaderRoute: typeof MTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kunde/$token': {
      id: '/kunde/$token'
      path: '/kunde/$token'
      fullPath: '/kunde/$token'
      preLoaderRoute: typeof KundeTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/b/$token': {
      id: '/b/$token'
      path: '/b/$token'
      fullPath: '/b/$token'
      preLoaderRoute: typeof BTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/verwaltung': {
      id: '/_authenticated/verwaltung'
      path: '/verwaltung'
      fullPath: '/verwaltung'
      preLoaderRoute: typeof AuthenticatedVerwaltungRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/statistik': {
      id: '/_authenticated/statistik'
      path: '/statistik'
      fullPath: '/statistik'
      preLoaderRoute: typeof AuthenticatedStatistikRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/posteingang': {
      id: '/_authenticated/posteingang'
      path: '/posteingang'
      fullPath: '/posteingang'
      preLoaderRoute: typeof AuthenticatedPosteingangRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/plan': {
      id: '/_authenticated/plan'
      path: '/plan'
      fullPath: '/plan'
      preLoaderRoute: typeof AuthenticatedPlanRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/nachrichten': {
      id: '/_authenticated/nachrichten'
      path: '/nachrichten'
      fullPath: '/nachrichten'
      preLoaderRoute: typeof AuthenticatedNachrichtenRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/mitarbeiter': {
      id: '/_authenticated/mitarbeiter'
      path: '/mitarbeiter'
      fullPath: '/mitarbeiter'
      preLoaderRoute: typeof AuthenticatedMitarbeiterRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/import': {
      id: '/_authenticated/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof AuthenticatedImportRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/export': {
      id: '/_authenticated/export'
      path: '/export'
      fullPath: '/export'
      preLoaderRoute: typeof AuthenticatedExportRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/einrichtungen': {
      id: '/_authenticated/einrichtungen'
      path: '/einrichtungen'
      fullPath: '/einrichtungen'
      preLoaderRoute: typeof AuthenticatedEinrichtungenRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dispo': {
      id: '/_authenticated/dispo'
      path: '/dispo'
      fullPath: '/dispo'
      preLoaderRoute: typeof AuthenticatedDispoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/bedarf': {
      id: '/_authenticated/bedarf'
      path: '/bedarf'
      fullPath: '/bedarf'
      preLoaderRoute: typeof AuthenticatedBedarfRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/anfragen': {
      id: '/_authenticated/anfragen'
      path: '/anfragen'
      fullPath: '/anfragen'
      preLoaderRoute: typeof AuthenticatedAnfragenRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/anfragen/mitarbeiter': {
      id: '/_authenticated/anfragen/mitarbeiter'
      path: '/mitarbeiter'
      fullPath: '/anfragen/mitarbeiter'
      preLoaderRoute: typeof AuthenticatedAnfragenMitarbeiterRouteImport
      parentRoute: typeof AuthenticatedAnfragenRoute
    }
    '/_authenticated/anfragen/kunden': {
      id: '/_authenticated/anfragen/kunden'
      path: '/kunden'
      fullPath: '/anfragen/kunden'
      preLoaderRoute: typeof AuthenticatedAnfragenKundenRouteImport
      parentRoute: typeof AuthenticatedAnfragenRoute
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/telegram/webhook': {
      id: '/api/public/telegram/webhook'
      path: '/api/public/telegram/webhook'
      fullPath: '/api/public/telegram/webhook'
      preLoaderRoute: typeof ApiPublicTelegramWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/email/inbound': {
      id: '/api/public/email/inbound'
      path: '/api/public/email/inbound'
      fullPath: '/api/public/email/inbound'
      preLoaderRoute: typeof ApiPublicEmailInboundRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAnfragenRouteChildren {
  AuthenticatedAnfragenKundenRoute: typeof AuthenticatedAnfragenKundenRoute
  AuthenticatedAnfragenMitarbeiterRoute: typeof AuthenticatedAnfragenMitarbeiterRoute
}

const AuthenticatedAnfragenRouteChildren: AuthenticatedAnfragenRouteChildren = {
  AuthenticatedAnfragenKundenRoute: AuthenticatedAnfragenKundenRoute,
  AuthenticatedAnfragenMitarbeiterRoute: AuthenticatedAnfragenMitarbeiterRoute,
}

const AuthenticatedAnfragenRouteWithChildren =
  AuthenticatedAnfragenRoute._addFileChildren(
    AuthenticatedAnfragenRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAnfragenRoute: typeof AuthenticatedAnfragenRouteWithChildren
  AuthenticatedBedarfRoute: typeof AuthenticatedBedarfRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDispoRoute: typeof AuthenticatedDispoRoute
  AuthenticatedEinrichtungenRoute: typeof AuthenticatedEinrichtungenRoute
  AuthenticatedExportRoute: typeof AuthenticatedExportRoute
  AuthenticatedImportRoute: typeof AuthenticatedImportRoute
  AuthenticatedMitarbeiterRoute: typeof AuthenticatedMitarbeiterRoute
  AuthenticatedNachrichtenRoute: typeof AuthenticatedNachrichtenRoute
  AuthenticatedPlanRoute: typeof AuthenticatedPlanRoute
  AuthenticatedPosteingangRoute: typeof AuthenticatedPosteingangRoute
  AuthenticatedStatistikRoute: typeof AuthenticatedStatistikRoute
  AuthenticatedVerwaltungRoute: typeof AuthenticatedVerwaltungRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAnfragenRoute: AuthenticatedAnfragenRouteWithChildren,
  AuthenticatedBedarfRoute: AuthenticatedBedarfRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDispoRoute: AuthenticatedDispoRoute,
  AuthenticatedEinrichtungenRoute: AuthenticatedEinrichtungenRoute,
  AuthenticatedExportRoute: AuthenticatedExportRoute,
  AuthenticatedImportRoute: AuthenticatedImportRoute,
  AuthenticatedMitarbeiterRoute: AuthenticatedMitarbeiterRoute,
  AuthenticatedNachrichtenRoute: AuthenticatedNachrichtenRoute,
  AuthenticatedPlanRoute: AuthenticatedPlanRoute,
  AuthenticatedPosteingangRoute: AuthenticatedPosteingangRoute,
  AuthenticatedStatistikRoute: AuthenticatedStatistikRoute,
  AuthenticatedVerwaltungRoute: AuthenticatedVerwaltungRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  BTokenRoute: BTokenRoute,
  KundeTokenRoute: KundeTokenRoute,
  MTokenRoute: MTokenRoute,
  TgVerfuegbarkeitRoute: TgVerfuegbarkeitRoute,
  VTokenRoute: VTokenRoute,
  ApiPublicEmailInboundRoute: ApiPublicEmailInboundRoute,
  ApiPublicTelegramWebhookRoute: ApiPublicTelegramWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
